### ISSUE TITLE
Implement set-interlock function

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-core#14]
Add support for the set-interlock command (function code 0xA2) in the extended protocol function set:

- [x] uhppote-core
- [x] uhppote-simulator
- [x] uhppote-cli
- [x] uhppoted-rest
- [x] uhppoted-mqtt
- [x] uhppoted-dll
- [x] uhppoted-codegen
- [x] nodered-contrib-uhppoted
- [x] uhppoted-nodejs
- [x] uhppoted-httpd
- [x] uhppoted

Ref. https://github.com/uhppoted/uhppoted-dll/issues/6

**Comment by twystd** [comment]
All done ... whew!
