### ISSUE TITLE
"Password management" functionality

### ISSUE THREAD

**Issue by fzakfeld** [uhppoted/uhppote-core#16]
The original Windows-based software for the generic access controlers have an option where you can configure "password management". There, you can set the option "Card + PIN" which needs to be turned on in order to ask for a PIN in addition to presenting the card. I did not find this option anywhere in the CLI, is it implemented or should we implement it ourselves and create a PR?

<img width="999" alt="image" src="https://github.com/uhppoted/uhppote-core/assets/43890789/901a08e9-bf43-4df2-a1a1-258274038420">

**Comment by uhppoted** [comment]
Hi,

Card PIN support was added in the last release but somehow the _Activate Keypad_ function got skipped over. 

I've added it to the current dev cycle. Unfortunately it requires implementation across about half the projects in the repo so it's going to take a while to complete in full, but if you can let me know which specific subsystem you are using I can give that priority.

**Comment by uhppoted** [comment]
Hi,

There is a preliminary implementation of _activate-keypads_ in _uhppote-core_ and _uhppote-cli_.

If you want to experiment with it, you'll need to build the trunk version of _uhppote-cli_ (it's straightforward - the instructions are [here](https://github.com/uhppoted/uhppote-cli#building-from-source)), and then the command to activate keypads is:
```
uhppote-cli activate-keypads <serial number> <keypads>

<serial number> access controller serial number
<keypads>       comma seperated list of readers for which to activate keypads.
                (keypads for unlisted readers are deactivated)

e.g.: uhppote-cli activate-keypads 405419896 1,4 
      activates the keypads for readers 1 and 4 and deactivates the keypads for readers 2 and 3.

```

**Comment by fzakfeld** [comment]
Thank you so much for the quick and detailed help! We will try that out, but since we can also set that option initially via the windows software, and it only needs to be done once, it is not that critical to us. Would be great if it will become available at some point though

**Comment by uhppoted** [comment]
Oh great! I shall work my way through the updating all the other places it also needs to be implemented.

Thanks for bringing it to my attention - had **completely** overlooked it and the PIN functionality isn't much use without it.

**Comment by uhppoted** [comment]
Hi,

Going to close this - it's been implemented across the board (cf. https://github.com/uhppoted/uhppoted/issues/35) and will be in the next release. Feel free to reopen if you need to though :-).
