### ISSUE TITLE
Add support for TCP/IP connections (also port 60000)

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-core#17]
Supplement the base level UDP driver with an optional TCP driver to simplify remote connections (e.g. across VPNs):

- [x] Verify controller support for TCP/IP
- [x] Add protocol field to controller struct
- [x] TCP driver implementation 
- [x] Add TCP support to simulator
- [x] ~~TCP events~~
- [x] Update dependents
- [x] NodeJS
- [x] NodeRED
- [x] Python
- [x] codegen
- [x] DLL
- [x] tunnel
- [x] httpd
- [x] HomeAssistant

**Comment by twystd** [comment]
Added support for TCP/IP transport throughout.
