### ISSUE TITLE
Replace Event pointer in GetStatusResponse with zero value

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-core#18]
Ref. https://github.com/uhppoted/uhppoted-dll/issues/7

Replace `Event` pointer in `GetStatusResponse` with struct and check for zero values rather than _nil_.

- [x] _uhppote-core_
- [x] _uhppoted-lib_
- [x] _uhppote-simulator_
- [x] _uhppote-cli_
- [x] _uhppoted-rest_
- [x] _uhppoted-mqtt_
- [x] _uhppoted-dll_
- [x] _uhppoted-codegen_
- [x] _uhppoted-httpd_
- [x] _uhppoted-tunnel_
- [x] _uhppoted-app-s3_
- [x] _uhppoted-app-sheets_
- [x] _uhppoted-app-wild-apricot_
- [x] _uhppoted-app-db_
- [x] _uhppoted-nodejs_
- [x] _nodered-contrib-uhppoted_
- [x] _uhppoted-python_

**Comment by twystd** [comment]
... finally done ... updated everything to handle `get-status` responses without an event.
