### ISSUE TITLE
set-event-listener: add auto-send interval

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-core#21]
Add the _auto-send interval_ to the _set-events-listener_ and _get-events-listener_ encodings and API functions:
- [x] _uhppote-core_
- [x] _uhppoted-lib_
- [x] _uhppote-simulator_
- [x] _uhppote-cli_
- [x] _uhppoted-rest_
- [x] _uhppoted-mqtt_
- [x] _uhppoted-dll_
- [x] _uhppoted-codegen_
- [x] _node-red-contrib-uhppoted_
- [x] _uhppoted-nodejs_
- [x] _uhppoted-python_
- [x] _uhppoted-tunnel_

**Comment by twystd** [comment]
Added auto-send interval to get/set-listener API functions throughout. Pending release v0.8.10
