### ISSUE TITLE
UHPPOTE PC control

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppote-core#7]
Implement `PC control` command.

**Comment by twystd** [comment]
TODO

- [ ] `uhppote-core`
- [ ] `uhppote-simulator`
- [ ] `node-red-contrib-uhppoted`
- [ ] `uhppoted-nodejs`
- [ ] `uhppoted-dll`
- [ ] `uhppoted-codegen`

**Comment by twystd** [comment]
Feature complete - pending release v0.8.4
